# Generated by Django 5.1.3 on 2024-11-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctors_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
