# Generated by Django 5.1.3 on 2024-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careproapp', '0002_appointment_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
