# Generated by Django 5.1.3 on 2024-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careproapp', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
